
---
events:
  -
    kind: "find-v1"
    backtrace:
      - "/opt/homebrew/share/cmake/Modules/CMakeDetermineSystem.cmake:12 (find_program)"
      - "CMakeLists.txt:16 (project)"
    mode: "program"
    variable: "CMAKE_UNAME"
    description: "Path to a program."
    settings:
      SearchFramework: "FIRST"
      SearchAppBundle: "FIRST"
      CMAKE_FIND_USE_CMAKE_PATH: true
      CMAKE_FIND_USE_CMAKE_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_SYSTEM_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_CMAKE_SYSTEM_PATH: true
      CMAKE_FIND_USE_INSTALL_PREFIX: true
    names:
      - "uname"
    candidate_directories:
      - "/private/var/folders/4r/ryq591ln7n94m62xq15x2kgw0000gn/T/pip-build-env-je9vtvkf/overlay/bin/"
      - "/private/var/folders/4r/ryq591ln7n94m62xq15x2kgw0000gn/T/pip-build-env-je9vtvkf/normal/bin/"
      - "/Users/prishapriyadashini/Downloads/DIMACS/SPLIT-ICML/split-env/bin/"
      - "/Library/Frameworks/Python.framework/Versions/3.12/bin/"
      - "/Users/prishapriyadashini/Library/Application Support/Code/User/globalStorage/github.copilot-chat/debugCommand/"
      - "/Users/prishapriyadashini/Library/Application Support/Code/User/globalStorage/github.copilot-chat/copilotCli/"
      - "/Library/Frameworks/Python.framework/Versions/3.11/bin/"
      - "/opt/homebrew/bin/"
      - "/opt/homebrew/sbin/"
      - "/usr/local/bin/"
      - "/System/Cryptexes/App/usr/bin/"
      - "/usr/bin/"
      - "/bin/"
      - "/usr/sbin/"
      - "/sbin/"
      - "/Library/Apple/usr/bin/"
      - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin/"
      - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin/"
      - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin/"
      - "/Users/prishapriyadashini/.vscode/extensions/ms-python.debugpy-2025.18.0-darwin-arm64/bundled/scripts/noConfigScripts/"
    searched_directories:
      - "/private/var/folders/4r/ryq591ln7n94m62xq15x2kgw0000gn/T/pip-build-env-je9vtvkf/overlay/bin/uname"
      - "/private/var/folders/4r/ryq591ln7n94m62xq15x2kgw0000gn/T/pip-build-env-je9vtvkf/normal/bin/uname"
      - "/Users/prishapriyadashini/Downloads/DIMACS/SPLIT-ICML/split-env/bin/uname"
      - "/Library/Frameworks/Python.framework/Versions/3.12/bin/uname"
      - "/Users/prishapriyadashini/Library/Application Support/Code/User/globalStorage/github.copilot-chat/debugCommand/uname"
      - "/Users/prishapriyadashini/Library/Application Support/Code/User/globalStorage/github.copilot-chat/copilotCli/uname"
      - "/Library/Frameworks/Python.framework/Versions/3.11/bin/uname"
      - "/opt/homebrew/bin/uname"
      - "/opt/homebrew/sbin/uname"
      - "/usr/local/bin/uname"
      - "/System/Cryptexes/App/usr/bin/uname"
    found: "/usr/bin/uname"
    search_context:
      ENV{PATH}:
        - "/private/var/folders/4r/ryq591ln7n94m62xq15x2kgw0000gn/T/pip-build-env-je9vtvkf/overlay/bin"
        - "/private/var/folders/4r/ryq591ln7n94m62xq15x2kgw0000gn/T/pip-build-env-je9vtvkf/normal/bin"
        - "/Users/prishapriyadashini/Downloads/DIMACS/SPLIT-ICML/split-env/bin"
        - "/Library/Frameworks/Python.framework/Versions/3.12/bin"
        - "/Users/prishapriyadashini/Library/Application Support/Code/User/globalStorage/github.copilot-chat/debugCommand"
        - "/Users/prishapriyadashini/Library/Application Support/Code/User/globalStorage/github.copilot-chat/copilotCli"
        - "/Library/Frameworks/Python.framework/Versions/3.11/bin"
        - "/opt/homebrew/bin"
        - "/opt/homebrew/sbin"
        - "/Library/Frameworks/Python.framework/Versions/3.12/bin"
        - "/usr/local/bin"
        - "/System/Cryptexes/App/usr/bin"
        - "/usr/bin"
        - "/bin"
        - "/usr/sbin"
        - "/sbin"
        - "/opt/homebrew/bin"
        - "/Library/Apple/usr/bin"
        - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin"
        - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin"
        - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin"
        - "/Users/prishapriyadashini/Library/Application Support/Code/User/globalStorage/github.copilot-chat/debugCommand"
        - "/Users/prishapriyadashini/Library/Application Support/Code/User/globalStorage/github.copilot-chat/copilotCli"
        - "/Library/Frameworks/Python.framework/Versions/3.12/bin"
        - "/Library/Frameworks/Python.framework/Versions/3.11/bin"
        - "/opt/homebrew/sbin"
        - "/Users/prishapriyadashini/.vscode/extensions/ms-python.debugpy-2025.18.0-darwin-arm64/bundled/scripts/noConfigScripts"
  -
    kind: "message-v1"
    backtrace:
      - "/opt/homebrew/share/cmake/Modules/CMakeDetermineSystem.cmake:212 (message)"
      - "CMakeLists.txt:16 (project)"
    message: |
      The system is: Darwin - 22.5.0 - arm64
  -
    kind: "find-v1"
    backtrace:
      - "/opt/homebrew/share/cmake/Modules/Platform/Darwin.cmake:76 (find_program)"
      - "/opt/homebrew/share/cmake/Modules/CMakeSystemSpecificInformation.cmake:32 (include)"
      - "CMakeLists.txt:16 (project)"
    mode: "program"
    variable: "CMAKE_INSTALL_NAME_TOOL"
    description: "Path to a program."
    settings:
      SearchFramework: "FIRST"
      SearchAppBundle: "FIRST"
      CMAKE_FIND_USE_CMAKE_PATH: true
      CMAKE_FIND_USE_CMAKE_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_SYSTEM_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_CMAKE_SYSTEM_PATH: true
      CMAKE_FIND_USE_INSTALL_PREFIX: true
    names:
      - "install_name_tool"
    candidate_directories:
      - "/private/var/folders/4r/ryq591ln7n94m62xq15x2kgw0000gn/T/pip-build-env-je9vtvkf/overlay/bin/"
      - "/private/var/folders/4r/ryq591ln7n94m62xq15x2kgw0000gn/T/pip-build-env-je9vtvkf/normal/bin/"
      - "/Users/prishapriyadashini/Downloads/DIMACS/SPLIT-ICML/split-env/bin/"
      - "/Library/Frameworks/Python.framework/Versions/3.12/bin/"
      - "/Users/prishapriyadashini/Library/Application Support/Code/User/globalStorage/github.copilot-chat/debugCommand/"
      - "/Users/prishapriyadashini/Library/Application Support/Code/User/globalStorage/github.copilot-chat/copilotCli/"
      - "/Library/Frameworks/Python.framework/Versions/3.11/bin/"
      - "/opt/homebrew/bin/"
      - "/opt/homebrew/sbin/"
      - "/usr/local/bin/"
      - "/System/Cryptexes/App/usr/bin/"
      - "/usr/bin/"
      - "/bin/"
      - "/usr/sbin/"
      - "/sbin/"
      - "/Library/Apple/usr/bin/"
      - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin/"
      - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin/"
      - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin/"
      - "/Users/prishapriyadashini/.vscode/extensions/ms-python.debugpy-2025.18.0-darwin-arm64/bundled/scripts/noConfigScripts/"
    searched_directories:
      - "/private/var/folders/4r/ryq591ln7n94m62xq15x2kgw0000gn/T/pip-build-env-je9vtvkf/overlay/bin/install_name_tool"
      - "/private/var/folders/4r/ryq591ln7n94m62xq15x2kgw0000gn/T/pip-build-env-je9vtvkf/normal/bin/install_name_tool"
      - "/Users/prishapriyadashini/Downloads/DIMACS/SPLIT-ICML/split-env/bin/install_name_tool"
      - "/Library/Frameworks/Python.framework/Versions/3.12/bin/install_name_tool"
      - "/Users/prishapriyadashini/Library/Application Support/Code/User/globalStorage/github.copilot-chat/debugCommand/install_name_tool"
      - "/Users/prishapriyadashini/Library/Application Support/Code/User/globalStorage/github.copilot-chat/copilotCli/install_name_tool"
      - "/Library/Frameworks/Python.framework/Versions/3.11/bin/install_name_tool"
      - "/opt/homebrew/bin/install_name_tool"
      - "/opt/homebrew/sbin/install_name_tool"
      - "/usr/local/bin/install_name_tool"
      - "/System/Cryptexes/App/usr/bin/install_name_tool"
    found: "/usr/bin/install_name_tool"
    search_context:
      ENV{PATH}:
        - "/private/var/folders/4r/ryq591ln7n94m62xq15x2kgw0000gn/T/pip-build-env-je9vtvkf/overlay/bin"
        - "/private/var/folders/4r/ryq591ln7n94m62xq15x2kgw0000gn/T/pip-build-env-je9vtvkf/normal/bin"
        - "/Users/prishapriyadashini/Downloads/DIMACS/SPLIT-ICML/split-env/bin"
        - "/Library/Frameworks/Python.framework/Versions/3.12/bin"
        - "/Users/prishapriyadashini/Library/Application Support/Code/User/globalStorage/github.copilot-chat/debugCommand"
        - "/Users/prishapriyadashini/Library/Application Support/Code/User/globalStorage/github.copilot-chat/copilotCli"
        - "/Library/Frameworks/Python.framework/Versions/3.11/bin"
        - "/opt/homebrew/bin"
        - "/opt/homebrew/sbin"
        - "/Library/Frameworks/Python.framework/Versions/3.12/bin"
        - "/usr/local/bin"
        - "/System/Cryptexes/App/usr/bin"
        - "/usr/bin"
        - "/bin"
        - "/usr/sbin"
        - "/sbin"
        - "/opt/homebrew/bin"
        - "/Library/Apple/usr/bin"
        - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin"
        - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin"
        - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin"
        - "/Users/prishapriyadashini/Library/Application Support/Code/User/globalStorage/github.copilot-chat/debugCommand"
        - "/Users/prishapriyadashini/Library/Application Support/Code/User/globalStorage/github.copilot-chat/copilotCli"
        - "/Library/Frameworks/Python.framework/Versions/3.12/bin"
        - "/Library/Frameworks/Python.framework/Versions/3.11/bin"
        - "/opt/homebrew/sbin"
        - "/Users/prishapriyadashini/.vscode/extensions/ms-python.debugpy-2025.18.0-darwin-arm64/bundled/scripts/noConfigScripts"
      CMAKE_INSTALL_PREFIX: "/usr/local"
...
